version: '3.8'

services:
  web:
    build: ./
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./db/init.sql:/init.sql
    entrypoint: >
      bash -c "
        echo '⏳ Waiting for SQL Server...';
        sleep 15;
        /opt/mssql-tools/bin/sqlcmd -S db -U sa -P Your_password123 -i /init.sql;
        echo '✅ init.sql exécuté avec succès.';"
